[versions]
# kotlin = "1.7.10"
moshi = "1.14.0"
assertk = "0.25"

[libraries]
kotlin-reflect = { module = "org.jetbrains.kotlinx:kotlinx-metadata-jvm", version = "0.5.0" }
moshi-core = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
moshi-adapters = { module = "com.squareup.moshi:moshi-adapters", version.ref = "moshi" }
assertk = { module = "com.willowtreeapps.assertk:assertk-jvm", version.ref = "assertk"}

[bundles]
moshi = ["moshi-core", "moshi-kotlin", "moshi-adapters"]
